name: Publish to npm

on:
  push:
    branches:
      - main  # Ou sua branch padrão, se for diferente
    tags:
      - 'v*'  # Executa o workflow para qualquer tag que comece com "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@eibii'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Substitua por seu comando de build, se necessário

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
